### PR TITLE
use fp-ts, prism and package json correctly

### PR DESCRIPTION
**Pull request by XVincentX**

### CODE REVIEW

**Comment by balanza** [comment]
Hi @XVincentX, many thanks for proposing those changes! Some of them were very useful (didn't notice that `prism-http-server` was bringing other packages as deps). However, I cannot still build it. 
When I `yarn install && yarn build` (or npm), I have the following error trace:

```
$ tsc
node_modules/@stoplight/prism-core/dist/logger.d.ts:1:23 - error TS7016: Could not find a declaration file for module 'pino'. '/Users/emanuele/Downloads/didactic-waffle/node_modules/pino/pino.js' implicitly has an 'any' type.
  Try `npm install @types/pino` if it exists or add a new declaration (.d.ts) file containing `declare module 'pino';`

1 import * as pino from 'pino';
                        ~~~~~~

node_modules/@stoplight/prism-core/dist/types.d.ts:3:30 - error TS2307: Cannot find module 'fp-ts/lib/ReaderEither'.

3 import { ReaderEither } from 'fp-ts/lib/ReaderEither';
                               ~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@stoplight/prism-core/dist/types.d.ts:6:24 - error TS7016: Could not find a declaration file for module 'pino'. '/Users/emanuele/Downloads/didactic-waffle/node_modules/pino/pino.js' implicitly has an 'any' type.
  Try `npm install @types/pino` if it exists or add a new declaration (.d.ts) file containing `declare module 'pino';`

6 import { Logger } from 'pino';
                         ~~~~~~

node_modules/@stoplight/prism-http-server/dist/types.d.ts:2:24 - error TS7016: Could not find a declaration file for module 'pino'. '/Users/emanuele/Downloads/didactic-waffle/node_modules/pino/pino.js' implicitly has an 'any' type.
  Try `npm install @types/pino` if it exists or add a new declaration (.d.ts) file containing `declare module 'pino';`

2 import { Logger } from 'pino';
                         ~~~~~~


Found 4 errors.
```

Do you get it to build?

**Comment by XVincentX** [comment]
That's expected. Declaration files should not be checked during the build process. Use `yarn build --skipLibCheck`

**Comment by balanza** [comment]
Ok, I understood I gave you the wrong example. Sorry, my bad.

Please try to use `fp-ts@1.12.0` instead of `fp-ts@1.19.2` and you will get a runtime error:

```
internal/modules/cjs/loader.js:983
  throw err;
  ^

Error: Cannot find module 'fp-ts/lib/pipeable'
Require stack:
- /Users/emanuele/Downloads/didactic-waffle/node_modules/@stoplight/prism-core/dist/factory.js
- /Users/emanuele/Downloads/didactic-waffle/node_modules/@stoplight/prism-core/dist/index.js
- /Users/emanuele/Downloads/didactic-waffle/node_modules/@stoplight/prism-http/dist/index.js
- /Users/emanuele/Downloads/didactic-waffle/src/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/emanuele/Downloads/didactic-waffle/node_modules/@stoplight/prism-core/dist/factory.js:5:20)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1040:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/emanuele/Downloads/didactic-waffle/node_modules/@stoplight/prism-core/dist/factory.js',
    '/Users/emanuele/Downloads/didactic-waffle/node_modules/@stoplight/prism-core/dist/index.js',
    '/Users/emanuele/Downloads/didactic-waffle/node_modules/@stoplight/prism-http/dist/index.js',
    '/Users/emanuele/Downloads/didactic-waffle/src/index.js'
  ]
}
```

I think it's because `prism-core` is using my application's `fp-ts` instead of the prism one. As prism works on fp-ts > 2, it fails.

Does it sound to you?

**Comment by XVincentX** [comment]
Yes, you've found something :)

Not all the dependencies were explicitly declared on the various packages.

https://github.com/stoplightio/prism/pull/1072

**Comment by balanza** [comment]
Great! We finally got it ;)

Thanks for support and for the quick fix!

**Pull request closed without merging**
